version: '3'

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=R00t5p455w0rd
      - MYSQL_DATABASE=gymappdb
      - MYSQL_PASSWORD=R00t5p455w0rd
    ports:
      - 3306:3306
  webapp:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
